In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

In [2]:
df = pd.read_csv("../raw/CrisisLexRec.txt", sep="\t", engine="python")

In [3]:
df.head()

      crisis_names
0     flood crisis
1          victims
2    flood victims
3   flood powerful
4  powerful storms

In [4]:
df[df.duplicated()]

Empty DataFrame
Columns: [crisis_names]
Index: []

In [5]:
sorted_df = df.sort_values(by="crisis_names",ascending = True)

In [6]:
sorted_df.head()

            crisis_names
158  accepting financial
19              affected
30        affected areas
109   affected explosion
60     affected flooding

In [7]:
sorted_df.shape

(379, 1)